### ISSUE TITLE
Get Parameter works but Set Parameter not

### ISSUE THREAD

**Issue by gnagflow80** [aaronsb/REC-BMSManager#4]
Hi Aaron, 
1st - it is realy great what you produce and share!!!
I experienced, that it is required to add the Group Serialout, if you use powershell for linux that it works.
But, only the get-BMSParameter works. When i use Set-BMSParameter it looks like:
![set-bms](https://user-images.githubusercontent.com/81044114/111883550-5651f200-89bc-11eb-917c-7f7f5ad46732.jpg)

It doesnt take the value, no matter iv you give the right confirmation instruction or not.

**Comment by gnagflow80** [comment]
It works only not on "CAPA", but it works on CLOW. Obviously there are some parameters changeable by your sofware, some not.

**Comment by aaronsb** [comment]
Can you try again and set the capa value to 1070.0 instead of 1070? Or otherwise cast it to float? I remained very strict about number types so you don't accidentally cast one to another and cause misadventure.

Perhaps an improvement would be to indicate that there was a number mismatch (int to float for example)

![image](https://user-images.githubusercontent.com/2738471/111893246-57404f00-89cf-11eb-89fa-54b09775ecb3.png)

**Comment by gnagflow80** [comment]
> 
> 
> Can you try again and set the capa value to 1070.0 instead of 1070? Or otherwise cast it to float? I remained very strict about number types so you don't accidentally cast one to another and cause misadventure.
> 
> Perhaps an improvement would be to indicate that there was a number mismatch (int to float for example)
> 
> ![image](https://user-images.githubusercontent.com/2738471/111893246-57404f00-89cf-11eb-89fa-54b09775ecb3.png)

Oh I see its a float. Alright, it is working now! Thanks a lot. --> now i try the MQTT & Grafana thing..
![grafik](https://user-images.githubusercontent.com/81044114/111896951-559d7800-8a1d-11eb-8f9b-2722c7925519.png)
